from .default import *

# DB
USUARIODB = "root"
CONTRASENADB = "12345"
# JWT

JWT_COOKIE_SECURE = True
JWT_COOKIE_CSRF_PROTECT = False
JWT_ACCESS_CSRF_HEADER_NAME = "X-CSRF-TOKEN-ACCESS"
JWT_REFRESH_CSRF_HEADER_NAME = "X-CSRF-TOKEN-REFRESH"
VALIDAR_URL = True
